#!/usr/bin/env node
/*
 * Flattens dist/miojslibs.d.ts (ambient module declarations generated by
 * `tsc --declaration --outfile`) into dist/miojslibs.global.d.ts, a global-scope
 * declaration file for consumers that use the classes as globals (the webpack
 * UMD bundle with no library name assigns every export onto the global object).
 *
 * Transformations, per `declare module "..."` block:
 *   - drop the module wrapper and dedent its body one level
 *   - drop import lines (every name is global in the output)
 *   - drop `export {};` markers and `export * from` barrel re-exports
 *   - unwrap `global { ... }` blocks (their contents are already global)
 *   - rewrite `export class/function/enum/var/let/const/interface/type`
 *     into top-level ambient declarations
 */

const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "..", "dist");
const inputFile = path.join(distDir, "miojslibs.d.ts");
const outputFile = path.join(distDir, "miojslibs.global.d.ts");

const INDENT = "    ";

const input = fs.readFileSync(inputFile, "utf8");
const lines = input.split("\n");

const out = [
    "// Auto-generated by tools/generate_global_dts.js from miojslibs.d.ts — do not edit.",
    "// Global-scope declarations for consumers that use MIOJSLibs classes as globals.",
    "",
];

let inModule = false;
let inGlobal = false;
let globalDepth = 0;

const braceDelta = (s) => (s.match(/\{/g) || []).length - (s.match(/\}/g) || []).length;

for (const rawLine of lines) {
    const line = rawLine.replace(/\r$/, "");

    if (!inModule) {
        if (/^declare module "/.test(line)) {
            inModule = true;
        }
        // anything outside a module block (blank lines, stray comments) is dropped
        continue;
    }

    // end of the current `declare module` block
    if (line === "}") {
        inModule = false;
        inGlobal = false;
        continue;
    }

    if (inGlobal) {
        globalDepth += braceDelta(line);
        if (globalDepth === 0) { // closing brace of `global {`
            inGlobal = false;
            continue;
        }
        out.push(line.startsWith(INDENT + INDENT) ? line.slice(INDENT.length * 2) : line);
        continue;
    }

    const body = line.startsWith(INDENT) ? line.slice(INDENT.length) : line;

    if (body === "global {") {
        inGlobal = true;
        globalDepth = 1;
        continue;
    }
    if (/^import[ ('"]/.test(body)) continue;
    if (/^export \{\};?$/.test(body)) continue;
    if (/^export \* from /.test(body)) continue;

    out.push(
        body
            .replace(/^export (class|abstract class|function|enum|const enum|var|let|const)\b/, "declare $1")
            .replace(/^export (interface|type)\b/, "$1")
    );
}

fs.writeFileSync(outputFile, out.join("\n") + "\n");
console.log(`Generated ${path.relative(process.cwd(), outputFile)} (${out.length} lines)`);
